#define NUM_VOLUME_LEDS 8
#define NUM_MAIN_LEDS 59
#define VOLUME_LED_DATA_PIN 4
#define MAIN_LED_DATA_PIN 2

#define ON_OFF_PIN 34
#define VOLUME_DOWN_PIN 32
#define VOLUME_UP_PIN 35

#define ON_LED_PIN 23
#define OFF_LED_PIN 22

#define WARM_LED_PIN 14
#define COLD_LED_PIN 27

#define PWM_FREQ 5000
#define LED_WARM_CHANNEL 0
#define LED_COLD_CHANNEL 1
#define RESOLUTION_WARM 8
#define RESOLUTION_COLD 10